xread
'TNT data for Graph 0 generated by PhylogeneticGraph (PhyG)'
2 17
Alentus 00	
Amblypygid	0?
Americhernus	01	
Aportus 12
Artemia	11
Centruoides	1?
Chanbria	12
Gea	10
Hadrurus	11
Hypochilus	11
Limulus	12
Mastigoproctus 13	
Pauroctonus	11
Rhiphicephalus	11
Thelichoris	11
Thermobius 11
Vonones	11
;
cc - 0.;
proc/;
