xread
'TNT data for Graph 0 generated by PhylogeneticGraph (PhyG)'
1 17
Alentus 0	
Amblypygid	0
Americhernus	0	
Aportus 1
Artemia	1
Centruoides	1
Chanbria	1
Gea	1
Hadrurus	1
Hypochilus	1
Limulus	1
Mastigoproctus 1	
Pauroctonus	1
Rhiphicephalus	1
Thelichoris	1
Thermobius 1
Vonones	-
;
cc - 0.;
cc /10 0.;
proc/;
